#!/usr/bin/env tsx
/**
 * Regenerate GithubArchiver memory views from append-only structured entries.
 *
 * Artifacts:
 *   - Timeline.md / Current Status.md / Project Digest.md / Knowledge Graph.md
 *   - indexes/<type>.md + convenience indexes
 *   - index.json (machine-readable retrieval index)
 *
 * Usage:
 *   npm run memory:timeline
 *   npm run memory:timeline:check
 */
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import {
	ENTRY_TYPES,
	type EntryType,
	type MemoryEntry,
	buildAliasIndex,
	defaultMemoryRoot,
	loadMemoryEntries,
	toMemoryIndex
} from '../src/lib/server/ai-memory.js';

const ROOT = defaultMemoryRoot();
const INDEXES_DIR = join(ROOT, 'indexes');
const CHECK = process.argv.includes('--check');

function linkRef(ref: string, aliases: Map<string, MemoryEntry>): string {
	const hit = aliases.get(ref);
	if (hit) return `[\`${ref}\`](${hit.relPath})`;
	return `\`${ref}\``;
}

function lineFor(e: MemoryEntry, aliases: Map<string, MemoryEntry>): string {
	const bits = [`**${e.date}**`, `\`${e.type}\``, `\`${e.confidence}\``, `\`${e.durability}\``];
	if (e.pr != null) bits.push(`PR #${e.pr}`);
	if (e.commit) bits.push(`\`${e.commit}\``);
	if (e.migration != null) bits.push(`migration ${e.migration}`);
	bits.push(`\`${e.status}\``);
	if (e.area.length) bits.push(e.area.map((a) => `\`${a}\``).join(', '));
	let line = `- ${bits.join(' · ')} — [${e.title}](${e.relPath})`;
	if (e.relationships.length) {
		line += `\n  - edges: ${e.relationships
			.map((r) => `${r.type}:${linkRef(r.id, aliases)}`)
			.join(', ')}`;
	}
	return line;
}

function genBanner(): string {
	return '> Generated by `npm run memory:timeline` from append-only `entries/*.md`. Do not edit by hand.';
}

function renderTimeline(entries: MemoryEntry[], aliases: Map<string, MemoryEntry>): string {
	const byDate = new Map<string, MemoryEntry[]>();
	for (const e of entries) {
		const list = byDate.get(e.date) ?? [];
		list.push(e);
		byDate.set(e.date, list);
	}
	const dates = [...byDate.keys()].sort((a, b) => (a < b ? 1 : -1));
	const sections = dates.map((date) => {
		const items = byDate.get(date)!;
		return `## ${date}\n\n${items.map((e) => lineFor(e, aliases)).join('\n')}`;
	});

	return [
		'---',
		'status: active',
		'project: githubarchiver',
		'type: timeline',
		'generated: true',
		'---',
		'',
		'# GithubArchiver Timeline',
		'',
		genBanner(),
		'',
		'Chronological event log (newest first). Source of truth is `entries/`.',
		'',
		...sections,
		''
	].join('\n');
}

function renderCurrentStatus(entries: MemoryEntry[], aliases: Map<string, MemoryEntry>): string {
	const open = entries.filter((e) => e.status === 'open' || e.status === 'open-debt');
	const recent = entries.filter((e) => e.status === 'merged' || e.status === 'verified').slice(0, 8);
	const debt = entries.filter((e) => e.type === 'technical-debt' || e.status === 'open-debt');
	const incidentsOpen = entries.filter((e) => e.type === 'incident' && e.status === 'open');

	return [
		'---',
		'status: active',
		'project: githubarchiver',
		'type: status',
		'generated: true',
		'---',
		'',
		'# Current Status',
		'',
		genBanner(),
		'',
		'Living summary derived from the entry log. For AI priming prefer [[Project Digest]].',
		'',
		'## Current architecture',
		'',
		'- GH Archive primary discovery; Search is fallback only',
		'- Background daemon plans ingest / enrich / archive / search_gap',
		'- Status UI: Current activity → Progress → Discovery',
		'- Orphan reconciliation covers `job_runs` and `search_ingest_stats`',
		'',
		'## Open work',
		'',
		open.length ? open.map((e) => lineFor(e, aliases)).join('\n') : '_None._',
		'',
		'## Open technical debt',
		'',
		debt.length ? debt.map((e) => lineFor(e, aliases)).join('\n') : '_None._',
		'',
		'## Active incidents',
		'',
		incidentsOpen.length ? incidentsOpen.map((e) => lineFor(e, aliases)).join('\n') : '_None._',
		'',
		'## Recent merges / verified',
		'',
		recent.length ? recent.map((e) => lineFor(e, aliases)).join('\n') : '_None._',
		'',
		'## Next priorities',
		'',
		'1. Merge/deploy open Search-fallback active accuracy fix and verify production table.',
		'2. Land memory system PRs; copy seed vault to `C:\\AI-Memory`.',
		'3. Confirm Railway `GITHUB_TOKEN` is real and quota-healthy.',
		''
	].join('\n');
}

function readOptional(name: string): string {
	try {
		return readFileSync(join(ROOT, name), 'utf8');
	} catch {
		return '';
	}
}

function extractBullets(md: string, limit: number): string {
	const bullets = md
		.split('\n')
		.map((l) => l.trim())
		.filter((l) => l.startsWith('- '));
	return bullets.slice(0, limit).join('\n');
}

function renderDigest(entries: MemoryEntry[], aliases: Map<string, MemoryEntry>): string {
	const principles = readOptional('Decisions.md');
	const architecture = readOptional('Architecture.md');
	const pitfalls = entries.filter((e) => e.type === 'incident').slice(0, 6);
	const recent = entries.slice(0, 8);
	const debt = entries.filter((e) => e.type === 'technical-debt' || e.status === 'open-debt');
	const open = entries.filter((e) => e.status === 'open');

	return [
		'---',
		'status: active',
		'project: githubarchiver',
		'type: digest',
		'generated: true',
		'---',
		'',
		'# Project Digest',
		'',
		genBanner(),
		'',
		'If an agent can load only one memory document, load this.',
		'',
		'## Purpose',
		'',
		'GithubArchive+ is an evidence-first GitHub repository intelligence platform: discover repos, enrich them, classify/cluster/score, tell Archive Stories, and preserve evidence.',
		'',
		'## Architecture',
		'',
		extractBullets(architecture, 12) ||
			'- SvelteKit + SQLite + GH Archive ingest + Search fallback + background daemon',
		'',
		'## Core principles',
		'',
		extractBullets(principles, 16) || '- See Decisions.md',
		'',
		'## Current pipeline',
		'',
		'Discovery (GH Archive → optional Search gap) → Ingestion → Enrichment → Clustering/scoring → Preservation. Daemon must not let enrichment backlog pause ingest. Status labels must match runtime behavior.',
		'',
		'## Known pitfalls',
		'',
		pitfalls.length
			? pitfalls
					.map((e) => `- [${e.title}](${e.relPath})${e.summary ? ` — ${e.summary}` : ''}`)
					.join('\n')
			: '_None recorded._',
		'',
		'## Recent changes',
		'',
		recent.map((e) => lineFor(e, aliases)).join('\n'),
		'',
		'## Open technical debt',
		'',
		debt.length ? debt.map((e) => lineFor(e, aliases)).join('\n') : '_None._',
		'',
		'## Current priorities',
		'',
		open.length ? open.map((e) => lineFor(e, aliases)).join('\n') : '_None open._',
		'',
		'## Important files',
		'',
		'- `src/lib/server/background-daemon.ts`',
		'- `src/lib/server/daemon-planner.ts`',
		'- `src/lib/server/gharchive.ts`',
		'- `src/lib/server/repo-discovery.ts`',
		'- `src/lib/server/db/search-ingest.ts`',
		'- `src/lib/components/StatusStory.svelte`',
		'- `src/lib/components/ActivityStatusBar.svelte`',
		'- `docs/ai-memory/seed/02 - Projects/GithubArchiver/entries/`',
		'- `docs/ai-memory/seed/02 - Projects/GithubArchiver/index.json`',
		''
	].join('\n');
}

function renderKnowledgeGraph(entries: MemoryEntry[], aliases: Map<string, MemoryEntry>): string {
	const lines = entries.map((e) => {
		const rel =
			e.relationships.length > 0
				? e.relationships
						.map((r) => `\`${r.type}\` → ${linkRef(r.id, aliases)}`)
						.join(', ')
				: '_none_';
		return `- [\`${e.id}\`](${e.relPath}) (\`${e.type}\`, \`${e.confidence}\`, \`${e.durability}\`) — ${e.title}\n  - ${rel}`;
	});

	return [
		'---',
		'status: active',
		'project: githubarchiver',
		'type: knowledge-graph',
		'generated: true',
		'---',
		'',
		'# Knowledge Graph',
		'',
		genBanner(),
		'',
		'Typed edges from `relationships:` (`caused-by`, `implemented-by`, `supersedes`, `references`, `validates`, `related`).',
		'',
		...lines,
		''
	].join('\n');
}

function renderTypeIndex(
	type: EntryType,
	entries: MemoryEntry[],
	aliases: Map<string, MemoryEntry>
): string {
	const items =
		type === 'migration'
			? entries.filter((e) => e.type === 'migration' || e.migration != null)
			: type === 'technical-debt'
				? entries.filter((e) => e.type === 'technical-debt' || e.status === 'open-debt')
				: entries.filter((e) => e.type === type);

	return [
		'---',
		'status: active',
		'project: githubarchiver',
		`type: ${type}-index`,
		'generated: true',
		'---',
		'',
		`# ${type}`,
		'',
		genBanner(),
		'',
		items.length ? items.map((e) => lineFor(e, aliases)).join('\n') : '_None yet._',
		''
	].join('\n');
}

function renderConvenience(
	title: string,
	items: MemoryEntry[],
	aliases: Map<string, MemoryEntry>,
	typeTag: string
): string {
	return [
		'---',
		'status: active',
		'project: githubarchiver',
		`type: ${typeTag}`,
		'generated: true',
		'---',
		'',
		`# ${title}`,
		'',
		genBanner(),
		'',
		items.length ? items.map((e) => lineFor(e, aliases)).join('\n') : '_None yet._',
		''
	].join('\n');
}

function writeOrCheck(path: string, content: string): boolean {
	if (CHECK) {
		let existing = '';
		try {
			existing = readFileSync(path, 'utf8');
		} catch {
			console.error(`missing generated file: ${path}`);
			return false;
		}
		if (existing !== content) {
			console.error(`out of date: ${path}`);
			return false;
		}
		return true;
	}
	mkdirSync(join(path, '..'), { recursive: true });
	writeFileSync(path, content);
	console.log(`wrote ${path}`);
	return true;
}

const entries = loadMemoryEntries(ROOT);
const aliases = buildAliasIndex(entries);
let ok = true;

// For check: compare entries payload only (ignore generatedAt wall clock).
if (CHECK) {
	try {
		const existing = JSON.parse(readFileSync(join(ROOT, 'index.json'), 'utf8')) as {
			entries: unknown;
		};
		const expected = toMemoryIndex(entries, 'x').entries;
		if (JSON.stringify(existing.entries) !== JSON.stringify(expected)) {
			console.error(`out of date: ${join(ROOT, 'index.json')}`);
			ok = false;
		}
	} catch {
		console.error(`missing generated file: ${join(ROOT, 'index.json')}`);
		ok = false;
	}
} else {
	const indexContent = `${JSON.stringify(toMemoryIndex(entries), null, 2)}\n`;
	writeFileSync(join(ROOT, 'index.json'), indexContent);
	console.log(`wrote ${join(ROOT, 'index.json')}`);
}

ok = writeOrCheck(join(ROOT, 'Timeline.md'), renderTimeline(entries, aliases)) && ok;
ok = writeOrCheck(join(ROOT, 'Current Status.md'), renderCurrentStatus(entries, aliases)) && ok;
ok = writeOrCheck(join(ROOT, 'Project Digest.md'), renderDigest(entries, aliases)) && ok;
ok = writeOrCheck(join(ROOT, 'Knowledge Graph.md'), renderKnowledgeGraph(entries, aliases)) && ok;

if (!CHECK) mkdirSync(INDEXES_DIR, { recursive: true });
for (const type of ENTRY_TYPES) {
	ok = writeOrCheck(join(INDEXES_DIR, `${type}.md`), renderTypeIndex(type, entries, aliases)) && ok;
}

ok =
	writeOrCheck(
		join(ROOT, 'PR Timeline.md'),
		renderConvenience(
			'PR Timeline',
			entries.filter((e) => e.pr != null),
			aliases,
			'pr-timeline'
		)
	) && ok;
ok =
	writeOrCheck(
		join(ROOT, 'Production Incidents.md'),
		renderConvenience(
			'Production Incidents',
			entries.filter((e) => e.type === 'incident'),
			aliases,
			'incidents'
		)
	) && ok;
ok =
	writeOrCheck(
		join(ROOT, 'Migrations.md'),
		renderConvenience(
			'Migrations',
			entries
				.filter((e) => e.type === 'migration' || e.migration != null)
				.slice()
				.sort((a, b) => (b.migration ?? 0) - (a.migration ?? 0)),
			aliases,
			'migrations'
		)
	) && ok;
ok =
	writeOrCheck(
		join(ROOT, 'Open Technical Debt.md'),
		renderConvenience(
			'Open Technical Debt',
			entries.filter((e) => e.type === 'technical-debt' || e.status === 'open-debt'),
			aliases,
			'debt'
		)
	) && ok;

const obsolete = join(ROOT, 'Architecture Decisions.md');
if (!CHECK) {
	try {
		rmSync(obsolete);
		console.log(`removed obsolete ${obsolete}`);
	} catch {
		/* absent */
	}
}

if (CHECK) {
	if (!ok) {
		console.error('Memory views are stale. Run: npm run memory:timeline');
		process.exit(1);
	}
	console.log(`ok: ${entries.length} entries`);
}
